name: 'run-notebook'
description: 'Run notebook'
author: 'yaananth'
inputs:
  notebook:
    description: 'Path to notebook with extension that should be executed'
    default: ''
  params:
    description: 'Path to parameters file with extension, contents should be json'
    default: '{}'
  isReport:
    description: 'If True, will hide inputs in notebook'
    default: False
  poll:
    description: 'If True, this will pool output every 15 seconds and displays, this is useful in cases where there's long running cells and user wants to see output after going to the page, since github actions doesn't show streaming from the beginning (but instead streams from the point user opens the page), this is a hack to get around it.'
    default: False
branding:
  icon: 'book'
  color: 'orange'
runs:
  using: 'node12'
  main: 'lib/main.js'
